
const items = [
  {
    id: '001',
    image: 'images/image1.webp',
    company: 'Tokyo Talkies',
    item_name: 'Women Full Sleeve Solid Sweatshirt',
    original_price: 1699,
    current_price: 391,
    discount_percentage: 76,
    return_period: 14,
    delivery_date: '20 Dec 2023',
    rating: {
      stars: 4.5,
      count: 1400,
    },
  },
  {
    id: '002',
    image: 'images/image2.webp',
    company: 'Tokyo Talkies',
    item_name: 'Women Solid Scoop Neck Green Sweater',
    original_price: 2049,
    current_price: 459,
    discount_percentage: 77,
    return_period: 14,
    delivery_date: '20 Dec 2023',
    rating: {
      stars: 4.5,
      count: 1400,
    },
  },
  {
    id: '003',
    image: 'images/image3.webp',
    company: 'Tokyo Talkies',
    item_name: 'Women Full Sleeve Printed Hooded Sweatshirt',
    original_price: 1799,
    current_price: 422,
    discount_percentage: 76,
    return_period: 14,
    delivery_date: '20 Dec 2023',
    rating: {
      stars: 4.5,
      count: 1400,
    },
  },
  {
    id: '004',
    image: 'images/image4.webp',
    company: 'Uptownie Lite',
    item_name: 'Women Self Design Casual Jacket',
    original_price: 2699,
    current_price: 549,
    discount_percentage: 79,
    return_period: 14,
    delivery_date: '20 Dec 2023',
    rating: {
      stars: 4.5,
      count: 1400,
    },
  },
  {
    id: '005',
    image: 'images/image5.webp',
    company: 'Magnolia',
    item_name: 'Modern Trendy Sneakers Sneakers For Men',
    original_price: 1299,
    current_price: 313,
    discount_percentage: 75,
    return_period: 14,
    delivery_date: '20 Dec 2023',
    rating: {
      stars: 4.5,
      count: 1400,
    },
  },
  {
    id: '006',
    image: 'images/image6.webp',
    company: 'BOLLERO',
    item_name: 'Sneaker Casual Shoes for Men Trendy Shoes ',
    original_price: 3999,
    current_price: 854,
    discount_percentage: 78,
    return_period: 14,
    delivery_date: '20 Dec 2023',
    rating: {
      stars: 4.5,
      count: 1400,
    },
  },
  {
    id: '007',
    image: 'images/image7.webp',
    company: 'Toriyox',
    item_name: 'Plastic PC Carbon Steel Collapsible wardrobe',
    original_price: 5499,
    current_price: 2022,
    discount_percentage: 63,
    return_period: 14,
    delivery_date: '20 Dec 2023',
    rating: {
      stars: 4.5,
      count: 1400,
    },
  },
  {
    id: '008',
    image: 'images/image8.webp',
    company: 'BVM GROUP',
    item_name: 'Writing Tablet 8.5 Inch Screen Electronic Wri...',
    original_price: 999,
    current_price: 145,
    discount_percentage: 85,
    return_period: 14,
    delivery_date: '20 Dec 2023',
    rating: {
      stars: 4.5,
      count: 1400,
    },
  },
  {
    id: '009',
    image: 'images/image9.webp',
    company: 'Do Pal',
    item_name: 'Air Dry Clay For Kids DIY Ultra Light Modeling B...',
    original_price: 499,
    current_price: 99,
    discount_percentage: 80,
    return_period: 14,
    delivery_date: '20 Dec 2023',
    rating: {
      stars: 4.5,
      count: 1400,
    },
  },
];
